package peer

import (
	"bufio"
	"context"
	"crypto/rand"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"sync"
	"sync/atomic"
	"time"

	"github.com/hashicorp/yamux"
)

// Role decides whether this peer acts as the yamux client or server. The role
// is asymmetric only for yamux's internal stream-ID allocation — at the
// channel layer both sides are equal and can open channels at will.
type Role int

const (
	RoleClient Role = iota
	RoleServer
)

// Peer represents one end of an established bidichan connection.
// It owns the yamux session, the control stream, and the channel registry.
type Peer struct {
	role    Role
	conn    net.Conn
	sess    *yamux.Session
	ctrl    *controlStream
	logger  *log.Logger
	doneCh  chan struct{}
	closeMu sync.Mutex
	closed  bool

	channels   sync.Map // channelID -> *channelState
	pending    sync.Map // channelID -> *pendingOpen (locally-initiated awaiting ack)
	nextChanID atomic.Uint64

	// Handlers maps each channel kind to the implementation that owns it.
	// Implementations are registered by the daemon before Start() is called.
	handlers map[ChannelKind]ChannelHandler

	// Metadata for status/CLI.
	id        string // peer identifier (auto-generated)
	startedAt time.Time
	remote    string
	local     string
}

// ChannelHandler is implemented by each channel kind to handle the local
// side of an open request (whether we originated or accepted it).
type ChannelHandler interface {
	// HandleOpen is called when the *responder* receives an OpenChannel for
	// this kind. It should set up any local resources (listener, tun device,
	// etc.) and return optional info to echo back in the ack. If error is
	// non-nil the open is naked back.
	HandleOpen(ctx context.Context, p *Peer, chID uint64, spec json.RawMessage) (json.RawMessage, ChannelRunner, error)

	// HandleOriginate is called when we initiated the open and the responder
	// has acked. It returns the local ChannelRunner so we can manage its
	// lifecycle on close.
	HandleOriginate(ctx context.Context, p *Peer, chID uint64, spec json.RawMessage, ackInfo json.RawMessage) (ChannelRunner, error)

	// HandleStream is called for each yamux data stream that arrives carrying
	// this channel's ID. The runner argument is whatever HandleOpen /
	// HandleOriginate returned. The handler reads/writes the stream until done
	// and closes it.
	HandleStream(ctx context.Context, p *Peer, runner ChannelRunner, stream net.Conn, meta json.RawMessage) error
}

// ChannelRunner is the per-channel state that lives between Open and Close.
// It is closed when the channel is torn down.
type ChannelRunner interface {
	io.Closer
	Description() string
}

// channelState tracks one open channel on this peer.
type channelState struct {
	id     uint64
	kind   ChannelKind
	spec   json.RawMessage
	runner ChannelRunner

	originator bool
	createdAt  time.Time

	cancel context.CancelFunc
}

// NewPeer constructs a Peer over an already-authenticated transport conn.
// id may be empty; if so a random id is generated by the caller.
// jitter returns base offset by a random amount in [-spread, +spread], so
// per-connection timers don't all fire on an identical cadence.
func jitter(base, spread time.Duration) time.Duration {
	if spread <= 0 {
		return base
	}
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return base
	}
	n := int64(binary.BigEndian.Uint64(b[:]) >> 1) // non-negative
	delta := time.Duration(n%(2*int64(spread)+1)) - spread
	return base + delta
}

func NewPeer(role Role, conn net.Conn, id string, logger *log.Logger) (*Peer, error) {
	if logger == nil {
		logger = log.Default()
	}
	yc := yamux.DefaultConfig()
	yc.LogOutput = nil
	yc.Logger = log.New(io.Discard, "", 0)
	// We already have keepalives on the TLS layer via TCP keepalive; yamux
	// keepalive adds a second layer that lets us notice peer death faster.
	// Jitter the interval per connection so the keepalive cadence isn't a
	// fixed 30s beat a traffic analyser could lock onto.
	yc.KeepAliveInterval = jitter(30*time.Second, 10*time.Second)
	yc.ConnectionWriteTimeout = 30 * time.Second
	yc.MaxStreamWindowSize = 1 << 20 // 1 MiB per stream

	var (
		sess *yamux.Session
		err  error
	)
	switch role {
	case RoleClient:
		sess, err = yamux.Client(conn, yc)
	case RoleServer:
		sess, err = yamux.Server(conn, yc)
	default:
		return nil, fmt.Errorf("peer: invalid role %d", role)
	}
	if err != nil {
		return nil, fmt.Errorf("yamux setup: %w", err)
	}

	p := &Peer{
		role:      role,
		conn:      conn,
		sess:      sess,
		logger:    logger,
		doneCh:    make(chan struct{}),
		handlers:  make(map[ChannelKind]ChannelHandler),
		id:        id,
		startedAt: time.Now(),
		remote:    conn.RemoteAddr().String(),
		local:     conn.LocalAddr().String(),
	}
	// Channel IDs are 64-bit; we partition the space so the two sides never
	// pick the same ID. Originator IDs are unique-per-peer but collisions
	// between peers are impossible because each ID is namespaced by the
	// peer's role bit in the high byte.
	if role == RoleServer {
		p.nextChanID.Store(1 << 62)
	}
	return p, nil
}

// RegisterHandler must be called before Start for each ChannelKind this peer
// will service.
func (p *Peer) RegisterHandler(k ChannelKind, h ChannelHandler) {
	p.handlers[k] = h
}

// ID returns the human-facing identifier for this peer.
func (p *Peer) ID() string { return p.id }

// RemoteAddr returns the remote network address.
func (p *Peer) RemoteAddr() string { return p.remote }

// LocalAddr returns the local network address.
func (p *Peer) LocalAddr() string { return p.local }

// StartedAt returns when the peer was constructed.
func (p *Peer) StartedAt() time.Time { return p.startedAt }

// Start establishes the control stream and begins serving incoming streams.
// For role=client the control stream is opened; for role=server it is
// accepted. Returns once setup is complete; the actual loops run in
// background goroutines until Close is called or the peer dies.
func (p *Peer) Start(ctx context.Context) error {
	var raw net.Conn
	var err error
	switch p.role {
	case RoleClient:
		raw, err = p.sess.OpenStream()
	case RoleServer:
		raw, err = p.sess.AcceptStream()
	}
	if err != nil {
		return fmt.Errorf("control stream: %w", err)
	}
	p.ctrl = newControlStream(raw, p.logger)

	go p.controlLoop(ctx)
	go p.streamLoop(ctx)
	return nil
}

// Done returns a channel closed when the peer has shut down.
func (p *Peer) Done() <-chan struct{} { return p.doneCh }

// Close tears down the peer. All channels are closed and the underlying
// transport is shut.
func (p *Peer) Close() error {
	p.closeMu.Lock()
	defer p.closeMu.Unlock()
	if p.closed {
		return nil
	}
	p.closed = true

	// Close every channel runner.
	p.channels.Range(func(_, v any) bool {
		st := v.(*channelState)
		if st.cancel != nil {
			st.cancel()
		}
		if st.runner != nil {
			_ = st.runner.Close()
		}
		return true
	})

	if p.ctrl != nil {
		_ = p.ctrl.Close()
	}
	_ = p.sess.Close()
	_ = p.conn.Close()
	close(p.doneCh)
	return nil
}

// streamLoop accepts new yamux streams initiated by the peer and dispatches
// them to the appropriate channel handler based on their header.
func (p *Peer) streamLoop(ctx context.Context) {
	for {
		s, err := p.sess.AcceptStream()
		if err != nil {
			if !errors.Is(err, io.EOF) && !errors.Is(err, yamux.ErrSessionShutdown) {
				p.logger.Printf("peer %s: accept stream: %v", p.id, err)
			}
			_ = p.Close()
			return
		}
		go p.handleStream(ctx, s)
	}
}

func (p *Peer) handleStream(ctx context.Context, s *yamux.Stream) {
	hdr, err := readStreamHeader(s)
	if err != nil {
		p.logger.Printf("peer %s: bad stream header: %v", p.id, err)
		_ = s.Close()
		return
	}
	v, ok := p.channels.Load(hdr.ChannelID)
	if !ok {
		p.logger.Printf("peer %s: stream for unknown channel %d", p.id, hdr.ChannelID)
		_ = s.Close()
		return
	}
	st := v.(*channelState)
	h, ok := p.handlers[st.kind]
	if !ok {
		p.logger.Printf("peer %s: no handler for kind %s", p.id, st.kind)
		_ = s.Close()
		return
	}
	if err := h.HandleStream(ctx, p, st.runner, s, hdr.Meta); err != nil {
		p.logger.Printf("peer %s: handle stream chan=%d: %v", p.id, hdr.ChannelID, err)
	}
}

// controlLoop reads control messages from the peer and dispatches them.
func (p *Peer) controlLoop(ctx context.Context) {
	defer p.Close()
	for {
		var env Envelope
		if err := p.ctrl.recv(&env); err != nil {
			if !errors.Is(err, io.EOF) {
				p.logger.Printf("peer %s: control recv: %v", p.id, err)
			}
			return
		}
		if err := p.dispatch(ctx, env); err != nil {
			p.logger.Printf("peer %s: dispatch: %v", p.id, err)
		}
	}
}

func (p *Peer) dispatch(ctx context.Context, env Envelope) error {
	switch env.Type {
	case MsgOpenChannel:
		var oc OpenChannel
		if err := json.Unmarshal(env.Payload, &oc); err != nil {
			return err
		}
		go p.handleOpen(ctx, oc)
		return nil
	case MsgOpenAck:
		var ack OpenAck
		if err := json.Unmarshal(env.Payload, &ack); err != nil {
			return err
		}
		return p.handleAck(ctx, ack, nil)
	case MsgOpenNack:
		var nack OpenNack
		if err := json.Unmarshal(env.Payload, &nack); err != nil {
			return err
		}
		return p.handleAck(ctx, OpenAck{ChannelID: nack.ChannelID}, errors.New(nack.Reason))
	case MsgCloseChannel:
		var cc CloseChannel
		if err := json.Unmarshal(env.Payload, &cc); err != nil {
			return err
		}
		p.handleClose(cc)
		return nil
	case MsgPing:
		return p.ctrl.send(Envelope{Type: MsgPong})
	case MsgPong:
		return nil
	default:
		return fmt.Errorf("unknown message type %q", env.Type)
	}
}

func (p *Peer) handleOpen(ctx context.Context, oc OpenChannel) {
	h, ok := p.handlers[oc.Kind]
	if !ok {
		_ = p.ctrl.send(Envelope{Type: MsgOpenNack, Payload: mustJSON(OpenNack{
			ChannelID: oc.ChannelID,
			Reason:    fmt.Sprintf("unsupported kind: %s", oc.Kind),
		})})
		return
	}
	chCtx, cancel := context.WithCancel(ctx)
	info, runner, err := h.HandleOpen(chCtx, p, oc.ChannelID, oc.Spec)
	if err != nil {
		cancel()
		_ = p.ctrl.send(Envelope{Type: MsgOpenNack, Payload: mustJSON(OpenNack{
			ChannelID: oc.ChannelID,
			Reason:    err.Error(),
		})})
		return
	}
	p.channels.Store(oc.ChannelID, &channelState{
		id:         oc.ChannelID,
		kind:       oc.Kind,
		spec:       oc.Spec,
		runner:     runner,
		originator: false,
		createdAt:  time.Now(),
		cancel:     cancel,
	})
	_ = p.ctrl.send(Envelope{Type: MsgOpenAck, Payload: mustJSON(OpenAck{
		ChannelID: oc.ChannelID,
		Info:      info,
	})})
}

// pendingOpen tracks a locally-originated OpenChannel waiting for ack.
type pendingOpen struct {
	kind ChannelKind
	spec json.RawMessage
	done chan pendingOpenResult
}

type pendingOpenResult struct {
	info json.RawMessage
	err  error
}

func (p *Peer) handleAck(ctx context.Context, ack OpenAck, err error) error {
	v, ok := p.pending.LoadAndDelete(ack.ChannelID)
	if !ok {
		return fmt.Errorf("ack for unknown pending channel %d", ack.ChannelID)
	}
	pend := v.(*pendingOpen)
	pend.done <- pendingOpenResult{info: ack.Info, err: err}
	return nil
}

func (p *Peer) handleClose(cc CloseChannel) {
	v, ok := p.channels.LoadAndDelete(cc.ChannelID)
	if !ok {
		return
	}
	st := v.(*channelState)
	if st.cancel != nil {
		st.cancel()
	}
	if st.runner != nil {
		_ = st.runner.Close()
	}
}

// OpenChannel originates a channel open. Returns the channel ID on success.
// kind selects the handler used to drive the local side after the responder
// acks. spec is the kind-specific JSON payload.
func (p *Peer) OpenChannel(ctx context.Context, kind ChannelKind, spec any) (uint64, error) {
	h, ok := p.handlers[kind]
	if !ok {
		return 0, fmt.Errorf("no local handler for kind %s", kind)
	}
	specJSON, err := json.Marshal(spec)
	if err != nil {
		return 0, fmt.Errorf("marshal spec: %w", err)
	}
	id := p.nextChanID.Add(1)
	done := make(chan pendingOpenResult, 1)
	pend := &pendingOpen{kind: kind, spec: specJSON, done: done}
	p.pending.Store(id, pend)
	defer p.pending.Delete(id)

	if err := p.ctrl.send(Envelope{Type: MsgOpenChannel, Payload: mustJSON(OpenChannel{
		ChannelID: id,
		Kind:      kind,
		Spec:      specJSON,
	})}); err != nil {
		return 0, fmt.Errorf("send open: %w", err)
	}

	select {
	case <-ctx.Done():
		return 0, ctx.Err()
	case res := <-done:
		if res.err != nil {
			return 0, res.err
		}
		chCtx, cancel := context.WithCancel(ctx)
		runner, err := h.HandleOriginate(chCtx, p, id, specJSON, res.info)
		if err != nil {
			cancel()
			_ = p.ctrl.send(Envelope{Type: MsgCloseChannel, Payload: mustJSON(CloseChannel{ChannelID: id, Reason: err.Error()})})
			return 0, err
		}
		p.channels.Store(id, &channelState{
			id:         id,
			kind:       kind,
			spec:       specJSON,
			runner:     runner,
			originator: true,
			createdAt:  time.Now(),
			cancel:     cancel,
		})
		return id, nil
	}
}

// CloseChannelByID asks the peer to tear down a channel. The local side is
// torn down immediately; the remote side is notified via the control stream.
func (p *Peer) CloseChannelByID(chID uint64, reason string) error {
	v, ok := p.channels.LoadAndDelete(chID)
	if !ok {
		return fmt.Errorf("no such channel: %d", chID)
	}
	st := v.(*channelState)
	if st.cancel != nil {
		st.cancel()
	}
	if st.runner != nil {
		_ = st.runner.Close()
	}
	return p.ctrl.send(Envelope{Type: MsgCloseChannel, Payload: mustJSON(CloseChannel{
		ChannelID: chID,
		Reason:    reason,
	})})
}

// OpenStream opens a new yamux stream and writes the given header to it. The
// returned net.Conn is ready for arbitrary data flow.
func (p *Peer) OpenStream(chID uint64, meta any) (net.Conn, error) {
	s, err := p.sess.OpenStream()
	if err != nil {
		return nil, err
	}
	var metaRaw json.RawMessage
	if meta != nil {
		b, err := json.Marshal(meta)
		if err != nil {
			_ = s.Close()
			return nil, err
		}
		metaRaw = b
	}
	if err := writeStreamHeader(s, StreamHeader{ChannelID: chID, Meta: metaRaw}); err != nil {
		_ = s.Close()
		return nil, err
	}
	return s, nil
}

// ChannelSnapshot is a CLI-friendly view of a single channel.
type ChannelSnapshot struct {
	ID          uint64      `json:"id"`
	Kind        ChannelKind `json:"kind"`
	Originator  bool        `json:"originator"`
	CreatedAt   time.Time   `json:"created_at"`
	Description string      `json:"description"`
}

// Snapshot returns a point-in-time view of open channels.
func (p *Peer) Snapshot() []ChannelSnapshot {
	var out []ChannelSnapshot
	p.channels.Range(func(_, v any) bool {
		st := v.(*channelState)
		desc := ""
		if st.runner != nil {
			desc = st.runner.Description()
		}
		out = append(out, ChannelSnapshot{
			ID:          st.id,
			Kind:        st.kind,
			Originator:  st.originator,
			CreatedAt:   st.createdAt,
			Description: desc,
		})
		return true
	})
	return out
}

// controlStream is the framed JSON channel both peers share for open/close
// signaling.
type controlStream struct {
	rwc    io.ReadWriteCloser
	r      *bufio.Reader
	w      *bufio.Writer
	wMu    sync.Mutex
	logger *log.Logger
}

func newControlStream(rwc io.ReadWriteCloser, logger *log.Logger) *controlStream {
	return &controlStream{
		rwc:    rwc,
		r:      bufio.NewReader(rwc),
		w:      bufio.NewWriter(rwc),
		logger: logger,
	}
}

func (cs *controlStream) Close() error { return cs.rwc.Close() }

func (cs *controlStream) send(env Envelope) error {
	cs.wMu.Lock()
	defer cs.wMu.Unlock()
	b, err := json.Marshal(env)
	if err != nil {
		return err
	}
	if _, err := cs.w.Write(b); err != nil {
		return err
	}
	if err := cs.w.WriteByte('\n'); err != nil {
		return err
	}
	return cs.w.Flush()
}

func (cs *controlStream) recv(env *Envelope) error {
	line, err := cs.r.ReadBytes('\n')
	if err != nil {
		return err
	}
	return json.Unmarshal(line, env)
}

func readStreamHeader(r io.Reader) (StreamHeader, error) {
	var lenBuf [4]byte
	if _, err := io.ReadFull(r, lenBuf[:]); err != nil {
		return StreamHeader{}, fmt.Errorf("read header len: %w", err)
	}
	n := binary.LittleEndian.Uint32(lenBuf[:])
	if n == 0 || n > 1<<16 {
		return StreamHeader{}, fmt.Errorf("header len out of range: %d", n)
	}
	buf := make([]byte, n)
	if _, err := io.ReadFull(r, buf); err != nil {
		return StreamHeader{}, fmt.Errorf("read header body: %w", err)
	}
	var h StreamHeader
	if err := json.Unmarshal(buf, &h); err != nil {
		return StreamHeader{}, fmt.Errorf("decode header: %w", err)
	}
	return h, nil
}

func writeStreamHeader(w io.Writer, h StreamHeader) error {
	b, err := json.Marshal(h)
	if err != nil {
		return err
	}
	if len(b) > 1<<16 {
		return fmt.Errorf("header too large: %d", len(b))
	}
	var lenBuf [4]byte
	binary.LittleEndian.PutUint32(lenBuf[:], uint32(len(b)))
	if _, err := w.Write(lenBuf[:]); err != nil {
		return err
	}
	_, err = w.Write(b)
	return err
}

func mustJSON(v any) json.RawMessage {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}
